import type { AgentSession, HistoryEntry } from "$lib/domain";

export const demoSessions: AgentSession[] = [
  {
    id: "codex-lume",
    agent: "codex",
    agentLabel: "Codex",
    controlOrigin: "external",
    project: "Lume",
    source: "vscode",
    status: "running",
    statusLabel: "Building the interface",
    startedAt: "2026-07-20T15:32:00-03:00",
    updatedAt: Date.now(),
    results: [],
    activities: [],
    permissionProfile: {
      mode: "workspace_write",
      label: "Project access",
      approvalPolicy: "Asks before leaving the workspace",
      canRespondFromLume: true,
      availableActions: ["allow_once", "deny"],
    },
  },
  {
    id: "claude-api",
    agent: "claude_code",
    agentLabel: "Claude Code",
    controlOrigin: "external",
    project: "Orbit API",
    source: "cli",
    status: "waiting_for_input",
    statusLabel: "Waiting for input",
    startedAt: "2026-07-20T15:28:00-03:00",
    updatedAt: Date.now() - 12_000,
    results: [],
    activities: [],
    permissionProfile: {
      mode: "read_only",
      label: "Read only",
      approvalPolicy: "Confirms changes and commands",
      canRespondFromLume: true,
      availableActions: ["allow_once", "allow_session", "deny"],
    },
  },
  {
    id: "gemini-web",
    agent: "gemini",
    agentLabel: "Gemini",
    controlOrigin: "external",
    project: "Research Hub",
    source: "web",
    status: "completed",
    statusLabel: "Completed 2 min ago",
    startedAt: "2026-07-20T15:18:00-03:00",
    updatedAt: Date.now() - 120_000,
    lastResponse: "I found the relevant references and grouped them by implementation approach.",
    results: [{
      id: "gemini-result-1",
      response: "I found the relevant references and grouped them by implementation approach.",
      createdAt: Date.now() - 120_000,
      files: ["references.md"],
      tests: [],
    }],
    activities: [],
    permissionProfile: {
      mode: "full_access",
      label: "Browser only",
      approvalPolicy: "Tab monitoring",
      canRespondFromLume: false,
      availableActions: ["open_source"],
    },
  },
];

export const demoHistory: HistoryEntry[] = [
  {
    id: "history-1",
    sessionId: "gemini-web",
    agentLabel: "Gemini",
    project: "Research Hub",
    event: "completed",
    summary: "Session completed",
    createdAt: Date.now() - 120_000,
  },
  {
    id: "history-2",
    sessionId: "codex-auth",
    agentLabel: "Codex",
    project: "auth-service",
    event: "permission_allowed",
    summary: "Permission granted once",
    createdAt: Date.now() - 38 * 60_000,
  },
];
